STRUCTURE = 'structure'
WEIGHT = 'weight'
SUPPLY_COST = 'supply_cost'
BUILD_LAIR = 'build_lair'
BUILD_HIVE = 'build_hive'
LOCATION = 'location'
SUPPLY_REQ = 'supply'
TOWNHALL_REQUIREMENT = 'townhall_req'
HATCH_1 = 'hatch1'
HATCH_2 = 'hatch2'
HATCH_3 = 'hatch3'
HATCH_4 = 'hatch4'
EXTRACTOR_1 = 'extractor1'
EXTRACTOR_2 = 'extractor2'
EXTRACTOR_3 = 'extractor3'
EXTRACTOR_4 = 'extractor4'
EXTRACTOR_COUNT = 'extractor_count'
BEFORE_HATCH = 'before_hatch'
# BUILD_ROACHWARREN = 'build_roach_warren'
# BUILD_HYDRADEN = 'build_hydra_den'
# BUILD_POOL = 'build_pool'
#
#
# MAX_ROACH = 'max_roach'
# MAX_HYDRA = 'max_hydra'
# MAX_LING = 'max_ling'
# MAX_DRONE = 'max_drone'
# MAX_OVERLORD = 'max_overlord'
#
# TIME_FOR_LAIR = 'time_for_lair'
#
# TRAIN_ROACH = 'train_roach'
# TRAIN_HYDRA = 'train_hydra'
# TRAIN_LING = 'train_ling'
# TRAIN_DRONE = 'train_drone'
# TRAIN_MUTA = 'train_muta'
# TRAIN_RAVAGER = 'train_ravager'
# TRAIN_BANELING = 'train_baneling'
# TRAIN_OVERSEER = 'train_overseer'
#
# SUPPLY_FOR_LAIR = 'supply_for_lair'
#
# # UPGRADES
# UPGRADE_ATTACK = 'upgrade_attack'
# UPGRADE_ARMOR = 'upgrade_armor'
# UPGRADE_LING_SPEED = 'upgrade_ling_speed'
# UPGRADE_OVERLORD_SPEED = 'upgrade_overlord_speed'
# UPGRADE_ADRENAL = 'upgrade_adrenal'

